### ISSUE TITLE
Only Show Hex In Edit Mode

### ISSUE THREAD

**Issue by vlopezjr** [branbarh/Trello-Colors-Extension#7]
When clicking on a label or adding a new label, the tool shows the hex code in the display.  It would be ideal if it was hidden at this level and that it would show the custom color.  The only place that it would make sense to show the hex code is in the "Edit Label" or "Create Label" screen.

![image](https://github.com/user-attachments/assets/0eebf442-700e-4bb1-b2a4-e782539156cd)

![image](https://github.com/user-attachments/assets/b292e4b7-b2ad-4fbf-9a05-1813ef18953b)

**Comment by branbarh** [comment]
This should be an easy fix, I'll work on this if I get time later today.

Thanks for submitting issues!

**Comment by vlopezjr** [comment]
No worries and thanks for creating the extension, very useful.

**Comment by branbarh** [comment]
Commit db44653 fixes this!

I decided to hide the hex code _everywhere_, including while editing labels.

Since the label editor acts as a label preview, displaying the hex code there when it isn't shown anywhere else doesn't feel cohesive.

Thanks again for submitting this issue! I'll take a look at fixing the colorblind patterns when I get a chance; I've already confirmed the issue on my end.
